---
title: "Assignment 5"
author: "Annie"
date: "16/10/2019"
output: github_document
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(gapminder)
library(tidyverse)
library(ggplot2)
library(here)
```

```{r}
gapminder$continent %>%
  str()
```

```{r}
oceania_dropped <- gapminder %>% 
  filter(continent != 'Oceania') %>%
  droplevels()

oceania_dropped

nlevels()
nrows()
```

```{r}
gap_max_gdp <- gapminder %>%
  group_by(continent) %>%
  summarize(max(gdpPercap)) %>%
  rename (max_gdp = 'max(gdpPercap)')
gap_max_gdp

gap_max_gdp %>%
  ggplot() +
  geom_col(aes(forcats::fct_relevel(continent, "Asia", "Europe", "Americas", "Oceania"), max_gdp)) +
  theme_bw() +
  ylab("Maximum GDP per Capita") + xlab("Continent")

#how to get fct_infreq to work?
```

```{r}
gap_africa_2000 <- gapminder %>%
  filter(continent == "Africa", year > 1999)
write_csv(gap_africa_2000, here::here("Assignment 5", "gap_africa_2000.csv"))
```


```{r}
read_csv(here("Assignment 5", "gap_africa_2000.csv"))
```


```{r}
```

